# Generated by Django 4.1.6 on 2023-02-14 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('germany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.PositiveIntegerField()),
                ('value2', models.PositiveIntegerField()),
                ('value3', models.PositiveIntegerField()),
                ('business_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='germany.businessplan')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='germany.country')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='germany.location')),
            ],
        ),
    ]
